locale: "en"
title: "Bob Rockefeller"
excerpt_separator: <!--more-->

tailwindcss:
  css_path: "./_tailwind.css"

exclude:
  - yarn.json
  - package.json
  - Gemfile
  - Gemfile.lock
  - .gitignore

jekyll_compose:
  default_front_matter:
    drafts:
      summary:
      image:
      category:
      tags:
    posts:
      summary:
      image:
      category:
      tags:

pagination:
  enabled: true
  per_page: 4
  extension:
  indexpage:
  sort_reverse: true
  trail:
    before: 2
    after: 2

defaults:
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      render_with_liquid: false
