locale: "en"
title: "Bob Rockefeller"

plugins:
  - jekyll-paginate-v2

exclude:
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - Gemfile
  - Gemfile.lock

jekyll_compose:
  default_front_matter:
    drafts:
      summary:
      image:
      category:
      tags:
    posts:
      summary:
      image:
      category:
      tags:

pagination:
  enabled: true
  per_page: 4
  extension:
  indexpage:
  sort_reverse: true
  trail:
    before: 2
    after: 2

defaults:
  - scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      render_with_liquid: false
