locale: "en"
title: "Bob Rockefeller"

collections:
  press:
    sort_by: date
    output: true
  donations:
    sort_by: year
    output: true

plugins:
  - jekyll-paginate-v2

exclude:
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - Gemfile
  - Gemfile.lock

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
    posts:
      description:
      image:
      category:
      tags:

pagination:
  enabled: true
  per_page: 4
  extension:
  indexpage:
