---
name: Bob Rockefeller
url: https://bobrockefeller.com
title: Bob Rockefeller
description: Welcome to my blog
menus:
  - name: Home
    url: "/"
  - name: About
    url: "/about"
  - name: Categories
    url: "/categories"
  - name: Tags
    url: "/tags"
---

